name: clean_books
description: A new Flutter project.
publish_to:
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  http: ^0.13.5
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  responsive_builder: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  